# # uncomment below lines to use CML
name: CML
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: |
          # Your ML wokflow commands
          pip install --upgrade pip
          pip install -r requirements.txt
          dvc repro -v
          echo "# REPORTS" >> report.md
          echo "## metrics" >> report.md
          cat scores.json >> report.md
          cml-send-comment report.md
        env:
          REPO_TOKEN: ${{ secrets._GITHUB_TOKEN }}